### ISSUE TITLE
Project Outline

### ISSUE THREAD

**Issue by vivianknee** [vivianknee/PocketTherapist#1]
# Project Plan: Your Pocket Therapist
 
## Project Overview
Your Pocket Therapist uses an AI Face algorithm to accurately understand the user's emotions and provide advice/quotes in response.
- Nighthawk pages frontend
- Spring portfolio backend

## Team Members
Vivian N
Isabelle G
Tanisha P
Sreeja G

## Project Objectives
1. Create a user-friendly interface
2. Create a live emotion detector, if make it so photos can be uploaded
3. Utilize a Face API to detect images and output emotions
4. Create our own unique database of advice and quotes that correspond to the emotions
5. Focus on JS for the frontend and Java for the backend

## Project Tasks and Timeline
1. Frontend (JS HTML)
- [ ] HTML Formatting (overall sass) 
- [ ] Container for Live Camera
- [ ] Section for Emotion recognizer result(with corresponding emoji), percent accuracy
- [ ] Section for generated quote (From API/Database call) 

2. Emotions AI (PYTHON)
- [ ] Open CV integration to live data collection 
- [ ] Find API/Data for the model -- RapidAPI
- [ ] Training/Testing 
- [ ] Display emotion result, save to global variable 
- [ ] Percent accuracy calculation 

3. Quote Generation (JAVA)
- [ ] Access quote based on saved emotion result 
- [ ] FIND API 
> https://rapidapi.com/karanp41-eRiF1pYLK1P/api/world-of-quotes
- [ ] Display successful api/database call
